package golib

// SUCCESS 成功
const SUCCESS = 1000

// PARAMETERERROR 参数错误
const PARAMETERERROR = 1001

// LOGINFAILED 登录失败
const LOGINFAILED = 1002

// TOKENFAILED token生成失败
const TOKENFAILED = 1003

// CREATEFAILED 数据库写入失败
const CREATEFAILED = 1004

// UPDATEFAILED 更新失败
const UPDATEFAILED = 1005

// SELECTFAILED 查找失败
const SELECTFAILED = 1006

// DELETEFAILED 删除失败
const DELETEFAILED = 1007

// UPLOADFAILED 文件上传失败
const UPLOADFAILED = 1008

// SERVERREQUESTFAILED 服务端请求失败
const SERVERREQUESTFAILED = 1009

//CALLFUNCTION 函数调用失败
const CALLFUNCTION = 1010

//REDISERROR 函数调用失败
const REDISERROR = 1011
